title: "Base de Datos de Impacto Económico de España (2020-2024)"
description: "Este dataset recopila indicadores macroecon&oacute;micos y financieros clave de Espa&ntilde;a para el per&iacute;odo 2020&ndash;2024. Incluye cinco ta"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/base-de-datos-de-impacto-economico-de-espana-2020-2024"
